### ISSUE TITLE
Research on Prisms interaction

### ISSUE THREAD

**Issue by darek607** [magic-script/magic-script-components-react-native#496]
I discussed with Sebastian the further steps of Prisms implementation.

The basic idea is:

1. Prism can be in one of the modes: **normal**,  **active** or **edit**.

2. Prism is **active** when the camera looks on it. In this mode we display a label with Prism's title, a button that activates the **edit** mode, and a button that closes the edit mode (and maybe more options in future).

3. In the **edit mode** we show the Prisms's boundary and user can manipulate the Prism (change its position, scale and rotation).

The mode can also be changed by setting a Prism's property. We will provide developers with listeners on mode change. There should be an option to enable only the desired functionality of Prisms interaction (highlighting, ways of possible manipulation, e.g. reposition only).

A nice feature would be a `lookAtCamera` property which would cause the Prism or the Prism's top menu is always rotated towards camera position, so user can always select the prism, without the need to rotate it manually.

As next steps we can provide a menu (a native view or better a JS component) from which the users could manage the Prisms.

**Comment by grozdanov** [comment]
MXSCOMP-211

**Comment by pleszkiewicz** [comment]
Questions:
1. What is the **normal** mode?
2. How can we turn **active** mode on?
- by looking at the prism?
3. Do we always show the buttons in **active** mode?
- in Lumin we need to press the Home button in order to show the menu with buttons or press Trigger fo a longer time to activate **edit** mode
4. What should happen when we are in **edit** mode and start looking around (or even move around)?
- there is a chance that we loose our **edited** prism
- should we then do not allow to lose the prism (always show it in front on the camera)
5. How do we want to manipulate the prism?
- how to move the prism? reticle interaction?
- how to rotate and scale the prism?

**Comment by darek607** [comment]
@pleszkiewicz 
1. **normal** mode: only the prism content is visible.
2.  Yes, Prism activates when camera looks at it.
3. Currently yes, but I think we could add a property to be able to disable this feature.
4. Currently on Android this prism is still in edit mode in such the case. This should be discussed.
5. Moving should be discussed, but we can follow the android PoC implementation: keeping finger on the prism and moving the device in 3d space moves the prism.

As for **scaling** on Android I used pinch gesture (the default provided by Sceneform). Similar gesture for rotating - touch the Prism with 2 fingers and rotate left / right (currently we support only the Y axis - most useful).

**Comment by kpiascik** [comment]
We want to allow the application to decide whether prisms manipulation is allowed or not.  The news app may want to allow prism manipulation, but others will not.
